# Generated by Django 4.0.1 on 2022-01-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate_project', '0005_alter_project_options_translator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='appointed_translator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translate_project.translator'),
        ),
    ]
